<h1><?php echo $this->translate('Sign In'); ?></h1>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>

<?php echo $this->form()->openTag($form) ?>
<dl class="zend_form">
    <?php foreach ($form as $element): ?>
        <?php if ($element->getLabel() != null && !$element instanceof Zend\Form\Element\Button): ?>
            <dt><?php echo $this->formLabel($element) ?></dt>
        <?php endif ?>
        <dd><?php echo $this->formElement($element) . $this->formElementErrors($element) ?></dd>
    <?php endforeach ?>
</dl>
<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>">
<?php endif ?>
<?php echo $this->form()->closeTag() ?>


<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>
